print("Sequence of numbers generated by following range expressios: range (5)")
for a in range(5):
    print(a)

print("Sequence of numbers generated by following range expressios: range (3, 10)")
for b in range(3,10):
    print(b)

print("Sequence of numbers generated by following range expressios: range (4, 13, 3)")    
for c in range(4,13,3):
    print(c)

print("Sequence of numbers generated by following range expressios: range (15, 5, -2)")
for d in range(15,5,-2):
    print(d)

print("Sequence of numbers generated by following range expressios: range (5, 3)")
for e in range(5,3,-1):
    print(e)
    
